services:
  # 2. Backend: Node.js
  backend:
    build: ./bsm-management-backend
    container_name: bsm_backend
    ports:
      - "5000:5000"
    env_file:
      - ./bsm-management-backend/.env
    environment:
      - DB_SERVER=host.docker.internal # Kết nối tới SQL Server trên máy host
    # Nếu bạn dùng database docker thì bỏ comment dòng dưới
    # depends_on:
    #   - database

  # 3. Frontend: React + Vite
  frontend:
    build: ./bsm-frontend
    container_name: bsm_frontend
    ports:
      - "5173:5173"
    stdin_open: true 
    tty: true        
    volumes:
      - ./bsm-frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  # SQL Server (Optional)
  # database:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   container_name: bsm_sql_server
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - MSSQL_SA_PASSWORD=YourStrong@Password
  #   ports:
  #     - "1434:1433"