services:
  # 2. Backend: Node.js
  backend:
    build: ./bsm-backend
    container_name: bsm_backend
    ports:
      - "5000:5000"
    env_file:
      - ./bsm-backend/.env
    environment:
      - DB_SERVER=host.docker.internal # Kết nối tới SQL Server trên máy host

  # 3. Frontend: React + Vite
  frontend:
    build: ./bsm-frontend
    container_name: bsm_frontend
    ports:
      - "5173:5173"
    stdin_open: true 
    tty: true        
    volumes:
      - ./bsm-frontend:/app
      - /app/node_modules
    depends_on:
      - backend
